#!/bin/bash
printf "{\n"
printf "\t"\"data"\":[\n"
printf "\t\t {\"{#PORT}\":\"22002\",\"{#SERVICE}\":\"accountService\"},\n"
printf "\t\t {\"{#PORT}\":\"22018\",\"{#SERVICE}\":\"guess-dataSyncService\"},\n"
printf "\t\t {\"{#PORT}\":\"22006\",\"{#SERVICE}\":\"guess-gateway\"},\n"
printf "\t\t {\"{#PORT}\":\"22017\",\"{#SERVICE}\":\"guess-query-service\"},\n"
printf "\t\t {\"{#PORT}\":\"22003\",\"{#SERVICE}\":\"guess-quotatePubService\"},\n"
printf "\t\t {\"{#PORT}\":\"22008\",\"{#SERVICE}\":\"guess-quotateSubService\"},\n"
printf "\t\t {\"{#PORT}\":\"22011\",\"{#SERVICE}\":\"guessScheduler\"},\n"
printf "\t\t {\"{#PORT}\":\"22004\",\"{#SERVICE}\":\"orderService\"},\n"
printf "\t\t {\"{#PORT}\":\"22015\",\"{#SERVICE}\":\"playService\"},\n"
printf "\t\t {\"{#PORT}\":\"22010\",\"{#SERVICE}\":\"portalService\"},\n"
printf "\t\t {\"{#PORT}\":\"22013\",\"{#SERVICE}\":\"pushService\"},\n"
printf "\t\t {\"{#PORT}\":\"22016\",\"{#SERVICE}\":\"quotate_gateway\"},\n"
printf "\t\t {\"{#PORT}\":\"22005\",\"{#SERVICE}\":\"riskCtlSystem\"},\n"
printf "\t\t {\"{#PORT}\":\"22001\",\"{#SERVICE}\":\"userService\"},\n"
printf "\t\t {\"{#PORT}\":\"22012\",\"{#SERVICE}\":\"zaService\"}\n"
printf "\t ]\n"
printf "}\n"
